# Generated by Django 5.1.6 on 2025-05-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=50)),
                ('order_number', models.CharField(max_length=50)),
                ('order_name', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField()),
                ('currency', models.CharField(max_length=10)),
                ('subtotal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('payment_method', models.CharField(max_length=50)),
                ('order_status', models.CharField(max_length=50)),
                ('products', models.TextField()),
                ('invoice_status', models.CharField(max_length=50)),
                ('email_status', models.CharField(max_length=50)),
                ('pdf_invoice', models.TextField(blank=True, null=True)),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
    ]
