# Generated by Django 5.1.6 on 2025-05-29 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=50)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.PositiveIntegerField()),
                ('audience_gender', models.CharField(max_length=20)),
                ('audience_start', models.PositiveIntegerField()),
                ('audience_end', models.PositiveIntegerField()),
                ('audience_interest', models.CharField(max_length=100)),
                ('ad_type', models.CharField(blank=True, max_length=100, null=True)),
                ('manual_ad_type', models.CharField(blank=True, max_length=100, null=True)),
                ('cta', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_strategies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetaAdStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=50)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.PositiveIntegerField()),
                ('audience_gender', models.CharField(max_length=20)),
                ('audience_start', models.PositiveIntegerField()),
                ('audience_end', models.PositiveIntegerField()),
                ('audience_interest', models.CharField(max_length=100)),
                ('ad_type', models.CharField(blank=True, max_length=100, null=True)),
                ('manual_ad_type', models.CharField(blank=True, max_length=100, null=True)),
                ('cta', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_strategies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
