# Generated by Django 5.1.6 on 2025-06-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_googleadstrategy_metaadstrategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaadstrategy',
            name='adset_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metaadstrategy',
            name='campaign_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
