# Generated by Django 5.1.6 on 2025-06-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_metaadstrategy_adset_id_metaadstrategy_campaign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaadstrategy',
            name='ad_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
