# Generated by Django 5.1.6 on 2025-06-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_metaadstrategy_ad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaadstrategy',
            name='creative_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
