# Generated by Django 5.1.6 on 2025-06-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_metaadstrategy_creative_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleadstrategy',
            name='ad_group_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='googleadstrategy',
            name='ad_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='googleadstrategy',
            name='campaign_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
