# Generated by Django 5.1.6 on 2025-06-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_googleadstrategy_ad_group_id_googleadstrategy_ad_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleadstrategy',
            name='create_ad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googleadstrategy',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googleadstrategy',
            name='final_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googleadstrategy',
            name='headlines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googleadstrategy',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googleadstrategy',
            name='target_location',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
