# Generated by Django 5.1.6 on 2025-06-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_googleadstrategy_create_ad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleadstrategy',
            name='app_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='googleadstrategy',
            name='app_store_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googleadstrategy',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
