"""
Django settings for new_db project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@your-secret-key-here'  # Replace with a secure key in production

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',  # Register the dashboard app
    'new_db'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'new_db.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Add templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'new_db.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'test',
        'USER': 'root',
        'PASSWORD': '12345',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field typeBASE_DIR
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',  # can be any string
    }
}

# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',  # db 1
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         }
#     }
# }



# settings.py
META_ACCESS_TOKEN = 'EAAQLL0WLotEBO7zOfH2nl5wGMuf9ZAdGEYDSQaZAgNUxdisokoEWzZAr3ETu3ZASZAjZA4S7RZCuXDeOQCOG7AOQZBng4vZAP2DjFSZBG0AZBIxnYM2eJighTj15N1Jml4aEr8dyzSkpRijyrw7kNdHK6YqmZCWPPtCzgyY0PKsRI6KybPA9xLxDUEd8a1lfKAaSe9R0ZATFFnrowpXfKkWSAoEZCmLZApqZBwZDZD'
META_AD_ACCOUNT_ID = 'act_723602407027376'
META_APP_ID = '1138197564990161'
META_APP_SECRET = '3e980c851dbf357b17c247ca357c2e88'

### 11-6 ###

META_PAGE_ID = '716457714878291'

META_PIXEL_ID = '1343440760087266'  # Replace with your Meta Pixel ID


### GOOGLE ###

GOOGLE_ADS_CLIENT_ID = '41808079414-5qteer3fjq3kgu4cjnpocmcaknj33jcq.apps.googleusercontent.com'
GOOGLE_ADS_CLIENT_SECRET = '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'
GOOGLE_ADS_REFRESH_TOKEN = '1//04aUcUzTtYpI_CgYIARAAGAQSNwF-L9IrdvF2y8eGotzIp9WxIW08uH2dZ1-vV2xLR3xoThJsvId4Shqh128eBmk5C44UKePg3mU'
GOOGLE_ADS_DEVELOPER_TOKEN = 'm8pFiY1Wdokmv6wWCCYeJg'
GOOGLE_ADS_CUSTOMER_ID = '7685269050'
GOOGLE_ADS_LOGIN_CUSTOMER_ID = '3799108591'  # ADD THIS!


YOUTUBE_API_KEY = 'AIzaSyBYvPitOHfFEA8zdsmm_LWSdCp57qPSC3c'
YOUTUBE_CHANNEL_ID = 'UCcSogXGk_HOVNCDXZUVydTQ'